# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientrpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import holoholo_shared_pb2 as holoholo__shared__pb2

from holoholo_shared_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='clientrpc.proto',
  package='Holoholo.Rpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x63lientrpc.proto\x12\x0cHoloholo.Rpc\x1a\x15holoholo_shared.protoP\x00\x62\x06proto3')
  ,
  dependencies=[holoholo__shared__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





# @@protoc_insertion_point(module_scope)
