# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import holoholo_shared_pb2 as holoholo__shared__pb2

from holoholo_shared_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='settings.proto',
  package='Holoholo.Rpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0esettings.proto\x12\x0cHoloholo.Rpc\x1a\x15holoholo_shared.proto\"\xda\x01\n\x11\x46ortSettingsProto\x12\x1e\n\x16InteractionRangeMeters\x18\x01 \x01(\x01\x12\x1f\n\x17MaxTotalDeployedPokemon\x18\x02 \x01(\x05\x12 \n\x18MaxPlayerDeployedPokemon\x18\x03 \x01(\x05\x12\x1f\n\x17\x44\x65ployStaminaMultiplier\x18\x04 \x01(\x01\x12\x1e\n\x16\x44\x65ployAttackMultiplier\x18\x05 \x01(\x01\x12!\n\x19\x46\x61rInteractionRangeMeters\x18\x06 \x01(\x01\"\xfb\x01\n\x10MapSettingsProto\x12\x1b\n\x13PokemonVisibleRange\x18\x01 \x01(\x01\x12\x1a\n\x12PokeNavRangeMeters\x18\x02 \x01(\x01\x12\x1c\n\x14\x45ncounterRangeMeters\x18\x03 \x01(\x01\x12&\n\x1eGetMapObjectsMinRefreshSeconds\x18\x04 \x01(\x02\x12&\n\x1eGetMapObjectsMaxRefreshSeconds\x18\x05 \x01(\x02\x12&\n\x1eGetMapObjectsMinDistanceMeters\x18\x06 \x01(\x02\x12\x18\n\x10GoogleMapsApiKey\x18\x07 \x01(\t\"R\n\x12LevelSettingsProto\x12\x19\n\x11TrainerCpModifier\x18\x02 \x01(\x01\x12!\n\x19TrainerDifficultyModifier\x18\x03 \x01(\x01\"~\n\x16InventorySettingsProto\x12\x12\n\nMaxPokemon\x18\x01 \x01(\x05\x12\x13\n\x0bMaxBagItems\x18\x02 \x01(\x05\x12\x13\n\x0b\x42\x61sePokemon\x18\x03 \x01(\x05\x12\x14\n\x0c\x42\x61seBagItems\x18\x04 \x01(\x05\x12\x10\n\x08\x42\x61seEggs\x18\x05 \x01(\x05\"\x99\x02\n\x13GlobalSettingsProto\x12\x35\n\x0c\x46ortSettings\x18\x02 \x01(\x0b\x32\x1f.Holoholo.Rpc.FortSettingsProto\x12\x33\n\x0bMapSettings\x18\x03 \x01(\x0b\x32\x1e.Holoholo.Rpc.MapSettingsProto\x12\x37\n\rLevelSettings\x18\x04 \x01(\x0b\x32 .Holoholo.Rpc.LevelSettingsProto\x12?\n\x11InventorySettings\x18\x05 \x01(\x0b\x32$.Holoholo.Rpc.InventorySettingsProto\x12\x1c\n\x14MinimumClientVersion\x18\x06 \x01(\tP\x00\x62\x06proto3')
  ,
  dependencies=[holoholo__shared__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FORTSETTINGSPROTO = _descriptor.Descriptor(
  name='FortSettingsProto',
  full_name='Holoholo.Rpc.FortSettingsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='InteractionRangeMeters', full_name='Holoholo.Rpc.FortSettingsProto.InteractionRangeMeters', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MaxTotalDeployedPokemon', full_name='Holoholo.Rpc.FortSettingsProto.MaxTotalDeployedPokemon', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MaxPlayerDeployedPokemon', full_name='Holoholo.Rpc.FortSettingsProto.MaxPlayerDeployedPokemon', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DeployStaminaMultiplier', full_name='Holoholo.Rpc.FortSettingsProto.DeployStaminaMultiplier', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DeployAttackMultiplier', full_name='Holoholo.Rpc.FortSettingsProto.DeployAttackMultiplier', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FarInteractionRangeMeters', full_name='Holoholo.Rpc.FortSettingsProto.FarInteractionRangeMeters', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=274,
)


_MAPSETTINGSPROTO = _descriptor.Descriptor(
  name='MapSettingsProto',
  full_name='Holoholo.Rpc.MapSettingsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PokemonVisibleRange', full_name='Holoholo.Rpc.MapSettingsProto.PokemonVisibleRange', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PokeNavRangeMeters', full_name='Holoholo.Rpc.MapSettingsProto.PokeNavRangeMeters', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EncounterRangeMeters', full_name='Holoholo.Rpc.MapSettingsProto.EncounterRangeMeters', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GetMapObjectsMinRefreshSeconds', full_name='Holoholo.Rpc.MapSettingsProto.GetMapObjectsMinRefreshSeconds', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GetMapObjectsMaxRefreshSeconds', full_name='Holoholo.Rpc.MapSettingsProto.GetMapObjectsMaxRefreshSeconds', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GetMapObjectsMinDistanceMeters', full_name='Holoholo.Rpc.MapSettingsProto.GetMapObjectsMinDistanceMeters', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GoogleMapsApiKey', full_name='Holoholo.Rpc.MapSettingsProto.GoogleMapsApiKey', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=528,
)


_LEVELSETTINGSPROTO = _descriptor.Descriptor(
  name='LevelSettingsProto',
  full_name='Holoholo.Rpc.LevelSettingsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TrainerCpModifier', full_name='Holoholo.Rpc.LevelSettingsProto.TrainerCpModifier', index=0,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TrainerDifficultyModifier', full_name='Holoholo.Rpc.LevelSettingsProto.TrainerDifficultyModifier', index=1,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=612,
)


_INVENTORYSETTINGSPROTO = _descriptor.Descriptor(
  name='InventorySettingsProto',
  full_name='Holoholo.Rpc.InventorySettingsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MaxPokemon', full_name='Holoholo.Rpc.InventorySettingsProto.MaxPokemon', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MaxBagItems', full_name='Holoholo.Rpc.InventorySettingsProto.MaxBagItems', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BasePokemon', full_name='Holoholo.Rpc.InventorySettingsProto.BasePokemon', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BaseBagItems', full_name='Holoholo.Rpc.InventorySettingsProto.BaseBagItems', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BaseEggs', full_name='Holoholo.Rpc.InventorySettingsProto.BaseEggs', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=614,
  serialized_end=740,
)


_GLOBALSETTINGSPROTO = _descriptor.Descriptor(
  name='GlobalSettingsProto',
  full_name='Holoholo.Rpc.GlobalSettingsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FortSettings', full_name='Holoholo.Rpc.GlobalSettingsProto.FortSettings', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MapSettings', full_name='Holoholo.Rpc.GlobalSettingsProto.MapSettings', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LevelSettings', full_name='Holoholo.Rpc.GlobalSettingsProto.LevelSettings', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='InventorySettings', full_name='Holoholo.Rpc.GlobalSettingsProto.InventorySettings', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MinimumClientVersion', full_name='Holoholo.Rpc.GlobalSettingsProto.MinimumClientVersion', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=743,
  serialized_end=1024,
)

_GLOBALSETTINGSPROTO.fields_by_name['FortSettings'].message_type = _FORTSETTINGSPROTO
_GLOBALSETTINGSPROTO.fields_by_name['MapSettings'].message_type = _MAPSETTINGSPROTO
_GLOBALSETTINGSPROTO.fields_by_name['LevelSettings'].message_type = _LEVELSETTINGSPROTO
_GLOBALSETTINGSPROTO.fields_by_name['InventorySettings'].message_type = _INVENTORYSETTINGSPROTO
DESCRIPTOR.message_types_by_name['FortSettingsProto'] = _FORTSETTINGSPROTO
DESCRIPTOR.message_types_by_name['MapSettingsProto'] = _MAPSETTINGSPROTO
DESCRIPTOR.message_types_by_name['LevelSettingsProto'] = _LEVELSETTINGSPROTO
DESCRIPTOR.message_types_by_name['InventorySettingsProto'] = _INVENTORYSETTINGSPROTO
DESCRIPTOR.message_types_by_name['GlobalSettingsProto'] = _GLOBALSETTINGSPROTO

FortSettingsProto = _reflection.GeneratedProtocolMessageType('FortSettingsProto', (_message.Message,), dict(
  DESCRIPTOR = _FORTSETTINGSPROTO,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:Holoholo.Rpc.FortSettingsProto)
  ))
_sym_db.RegisterMessage(FortSettingsProto)

MapSettingsProto = _reflection.GeneratedProtocolMessageType('MapSettingsProto', (_message.Message,), dict(
  DESCRIPTOR = _MAPSETTINGSPROTO,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:Holoholo.Rpc.MapSettingsProto)
  ))
_sym_db.RegisterMessage(MapSettingsProto)

LevelSettingsProto = _reflection.GeneratedProtocolMessageType('LevelSettingsProto', (_message.Message,), dict(
  DESCRIPTOR = _LEVELSETTINGSPROTO,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:Holoholo.Rpc.LevelSettingsProto)
  ))
_sym_db.RegisterMessage(LevelSettingsProto)

InventorySettingsProto = _reflection.GeneratedProtocolMessageType('InventorySettingsProto', (_message.Message,), dict(
  DESCRIPTOR = _INVENTORYSETTINGSPROTO,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:Holoholo.Rpc.InventorySettingsProto)
  ))
_sym_db.RegisterMessage(InventorySettingsProto)

GlobalSettingsProto = _reflection.GeneratedProtocolMessageType('GlobalSettingsProto', (_message.Message,), dict(
  DESCRIPTOR = _GLOBALSETTINGSPROTO,
  __module__ = 'settings_pb2'
  # @@protoc_insertion_point(class_scope:Holoholo.Rpc.GlobalSettingsProto)
  ))
_sym_db.RegisterMessage(GlobalSettingsProto)


# @@protoc_insertion_point(module_scope)
