# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sfida.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sfida.proto',
  package='Holoholo.Rpc',
  syntax='proto3',
  serialized_pb=_b('\n\x0bsfida.proto\x12\x0cHoloholo.Rpc\"\x90\x03\n\rPokemonGoPlus\x1a\x98\x01\n\x0ePgpEntryPoints\"\x85\x01\n\x08\x41piError\x12\x0b\n\x07SUCCESS\x10\x00\x12\x14\n\x10PLUGIN_NOT_READY\x10\x01\x12\x11\n\rNOT_SUPPORTED\x10\x02\x12\x17\n\x13NOT_IMPLEMENTED_YET\x10\x03\x12\x12\n\x0eINTERNAL_ERROR\x10\x04\x12\x16\n\x12INVALID_PARAMETERS\x10\x05\"n\n\x0c\x43\x65ntralState\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tRESETTING\x10\x01\x12\x0f\n\x0bUNSUPPORTED\x10\x02\x12\x10\n\x0cUNAUTHORIZED\x10\x03\x12\x0f\n\x0bPOWERED_OFF\x10\x04\x12\x0e\n\nPOWERED_ON\x10\x05\"t\n\x11SfidaConnectState\x12\x10\n\x0c\x44ISCONNECTED\x10\x00\x12\r\n\tCONNECTED\x10\x01\x12\x0e\n\nDISCOVERED\x10\x02\x12\r\n\tCERTIFIED\x10\x03\x12\x13\n\x0fSOFTWARE_UPDATE\x10\x04\x12\n\n\x06\x46\x41ILED\x10\x05\"\'\n\x14RegisterSfidaRequest\x12\x0f\n\x07SfidaId\x18\x01 \x01(\t\",\n\x15RegisterSfidaResponse\x12\x13\n\x0b\x41\x63\x63\x65ssToken\x18\x01 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_POKEMONGOPLUS_PGPENTRYPOINTS_APIERROR = _descriptor.EnumDescriptor(
  name='ApiError',
  full_name='Holoholo.Rpc.PokemonGoPlus.PgpEntryPoints.ApiError',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLUGIN_NOT_READY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_SUPPORTED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_IMPLEMENTED_YET', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_PARAMETERS', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=67,
  serialized_end=200,
)
_sym_db.RegisterEnumDescriptor(_POKEMONGOPLUS_PGPENTRYPOINTS_APIERROR)

_POKEMONGOPLUS_CENTRALSTATE = _descriptor.EnumDescriptor(
  name='CentralState',
  full_name='Holoholo.Rpc.PokemonGoPlus.CentralState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESETTING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSUPPORTED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNAUTHORIZED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POWERED_OFF', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POWERED_ON', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=202,
  serialized_end=312,
)
_sym_db.RegisterEnumDescriptor(_POKEMONGOPLUS_CENTRALSTATE)

_POKEMONGOPLUS_SFIDACONNECTSTATE = _descriptor.EnumDescriptor(
  name='SfidaConnectState',
  full_name='Holoholo.Rpc.PokemonGoPlus.SfidaConnectState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCOVERED', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CERTIFIED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTWARE_UPDATE', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=314,
  serialized_end=430,
)
_sym_db.RegisterEnumDescriptor(_POKEMONGOPLUS_SFIDACONNECTSTATE)


_POKEMONGOPLUS_PGPENTRYPOINTS = _descriptor.Descriptor(
  name='PgpEntryPoints',
  full_name='Holoholo.Rpc.PokemonGoPlus.PgpEntryPoints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POKEMONGOPLUS_PGPENTRYPOINTS_APIERROR,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=200,
)

_POKEMONGOPLUS = _descriptor.Descriptor(
  name='PokemonGoPlus',
  full_name='Holoholo.Rpc.PokemonGoPlus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_POKEMONGOPLUS_PGPENTRYPOINTS, ],
  enum_types=[
    _POKEMONGOPLUS_CENTRALSTATE,
    _POKEMONGOPLUS_SFIDACONNECTSTATE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=430,
)


_REGISTERSFIDAREQUEST = _descriptor.Descriptor(
  name='RegisterSfidaRequest',
  full_name='Holoholo.Rpc.RegisterSfidaRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SfidaId', full_name='Holoholo.Rpc.RegisterSfidaRequest.SfidaId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=471,
)


_REGISTERSFIDARESPONSE = _descriptor.Descriptor(
  name='RegisterSfidaResponse',
  full_name='Holoholo.Rpc.RegisterSfidaResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccessToken', full_name='Holoholo.Rpc.RegisterSfidaResponse.AccessToken', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=517,
)

_POKEMONGOPLUS_PGPENTRYPOINTS.containing_type = _POKEMONGOPLUS
_POKEMONGOPLUS_PGPENTRYPOINTS_APIERROR.containing_type = _POKEMONGOPLUS_PGPENTRYPOINTS
_POKEMONGOPLUS_CENTRALSTATE.containing_type = _POKEMONGOPLUS
_POKEMONGOPLUS_SFIDACONNECTSTATE.containing_type = _POKEMONGOPLUS
DESCRIPTOR.message_types_by_name['PokemonGoPlus'] = _POKEMONGOPLUS
DESCRIPTOR.message_types_by_name['RegisterSfidaRequest'] = _REGISTERSFIDAREQUEST
DESCRIPTOR.message_types_by_name['RegisterSfidaResponse'] = _REGISTERSFIDARESPONSE

PokemonGoPlus = _reflection.GeneratedProtocolMessageType('PokemonGoPlus', (_message.Message,), dict(

  PgpEntryPoints = _reflection.GeneratedProtocolMessageType('PgpEntryPoints', (_message.Message,), dict(
    DESCRIPTOR = _POKEMONGOPLUS_PGPENTRYPOINTS,
    __module__ = 'sfida_pb2'
    # @@protoc_insertion_point(class_scope:Holoholo.Rpc.PokemonGoPlus.PgpEntryPoints)
    ))
  ,
  DESCRIPTOR = _POKEMONGOPLUS,
  __module__ = 'sfida_pb2'
  # @@protoc_insertion_point(class_scope:Holoholo.Rpc.PokemonGoPlus)
  ))
_sym_db.RegisterMessage(PokemonGoPlus)
_sym_db.RegisterMessage(PokemonGoPlus.PgpEntryPoints)

RegisterSfidaRequest = _reflection.GeneratedProtocolMessageType('RegisterSfidaRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERSFIDAREQUEST,
  __module__ = 'sfida_pb2'
  # @@protoc_insertion_point(class_scope:Holoholo.Rpc.RegisterSfidaRequest)
  ))
_sym_db.RegisterMessage(RegisterSfidaRequest)

RegisterSfidaResponse = _reflection.GeneratedProtocolMessageType('RegisterSfidaResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERSFIDARESPONSE,
  __module__ = 'sfida_pb2'
  # @@protoc_insertion_point(class_scope:Holoholo.Rpc.RegisterSfidaResponse)
  ))
_sym_db.RegisterMessage(RegisterSfidaResponse)


# @@protoc_insertion_point(module_scope)
